function __m_usage
    echo "Usage: m [COMMAND]"
    echo
    echo "where COMMAND can be one of:"
    echo "       battery"
    echo "       bluetooth"
    echo "       dir"
    echo "       disk"
    echo "       dns"
    echo "       dock"
    echo "       finder"
    echo "       firewall"
    echo "       gatekeeper"
    echo "       hostname"
    echo "       info"
    echo "       lock"
    echo "       ntp"
    echo "       network"
    echo "       nosleep"
    echo "       restart"
    echo "       safeboot"
    echo "       screensaver"
    echo "       service"
    echo "       shutdown"
    echo "       sleep"
    echo "       timezone"
    echo "       trash"
    echo "       update"
    echo "       user"
    echo "       volume"
    echo "       vpn"
    echo "       wallpaper"
    echo "       wifi"
end
